export class PermissionItemsEnum {

    public static readonly values = [
        'View Status',
        'View Status Group',
        'View Status All',
        'View Account Statement',
        'View Agreements',
        'View Agreements All',
        'Create Agreements',
        'Edit Agreements',
        'Delete Agreements',
        'Print Agreement PDF',
        'Send Agreement Email',
        'View Claims',
        'Create Claims',
        'Delete Claims',
        'Change Claims Status',
        'Print Claims PDF',
        'View Invoice',
        'Change Invoice Status',
        'Print Invoice PDF',
        'View All Accounts',
        'View Their Account(s)',
        'Create Accounts',
        'edit Accounts',
        'Inactivate Accounts',
        'Edit Direct Debit Details',
        'Change Pricing Exceptions',
        'Change User Type',
        'View Administration Charge',
        'Change Administration Charge',
        'View Commission',
        'Change Commission',
        'View Commission Rules Theirs',
        'View Commission Rules of All',
        'Change Commission Rules',
        'View Commission Sheet',
        'View Commission Sheets All',
        'Print Commission PDF',
        'View Pricing',
        'Create Pricing',
        'Edit Pricing',
        'Allow Custom Pricing',
        'Create Custom Pricing',
        'Refunds View',
        'View Refund Rules',
        'View Payments',
        'Add Payments',
        'Edit Payments',
        'Delete Payments',
        'View Payment Received',
        'Add Payment Received',
        'Edit Payment Received',
        'Delete Payment Received',
        'Change Business VAT',
        'View Permission Profile',
        'Create Permission Profile',
        'Edit Permission Profile',
        'Delete Permission Profile',
        'Create Group',
        'Edit Group',
        'Allocate Group',
        'View Scheduled Tasks',
        'Create Schedule Task',
        'Edit Scheduled Task',
        'Delete Scheduled Task',
        'View Covered Parts',
        'Edit Covered Parts',
    ];
}
